Add small testsuite and standardize pkg var in functions

diff --git a/sli b/sli
--- a/sli
+++ b/sli
@@ -265,6 +265,18 @@ sli_install() {
 	pkg_post_install
 }
 
+sli_testsuite() {
+	print_header "⚡️ SLi Testsuite"
+	echo -e "Colors: ${PURPLE}purple${NC} ${CYAN}cyan${NC} ${YELLOW}yellow${NC} ${RED}red${NC} ${GREEN}green${NC}"
+	echo -n "pkg_get_version sli: "; pkg_get_version sli
+	if [ -f "debug_recipe.sh" ]; then
+		echo ""
+		pkg_install "debug"
+		echo ""
+		pkg_remove "debug"
+	fi
+}
+
 # Let user use lit in place of litd. also used to check file exist (ie litd.service)
 service_check() {
 	if [ -z "$2" ]; then
@@ -1606,30 +1618,30 @@ EOT
 # Packages recipes can be downloaded individualy since they can be updated
 # or added without a new SLi release.
 pkg_get_recipe() {
-	local action="$1" package="$2"
+	local action="$1" pkg="$2"
 	
-	# Check if package exist
-	if ! grep -q "^${package}|" ${PKGS_LIST}; then
-		error "Package ${RED}$package${NC} don't exist"
+	# Check if package exist in DB or a recipe in current dir
+	if ! grep -q "^${pkg}|" ${PKGS_LIST} && [ ! -f ${pkg}_recipe.sh ]; then
+		error "Package ${RED}$pkg${NC} don't exist"
 	else
 		# Ensure local recipes dir exist
 		mkdir -p ${PKGS_RECIPES}
 	fi
 	
 	# sli get-recipe <pkg>
-	if [ "$action" == "get" ] && [ ! -f ${package}_recipe.sh ]; then
-		echo -e "Downloading ${CYAN}$package${NC} recipe..."
-		wget -q --show-progress ${PKGS_RECIPES_URL}/${package}_recipe.sh
+	if [ "$action" == "get" ] && [ ! -f ${pkg}_recipe.sh ]; then
+		echo -e "Downloading ${CYAN}$pkg${NC} recipe..."
+		wget -q --show-progress ${PKGS_RECIPES_URL}/${pkg}_recipe.sh
 	
 	# No download if recipe exist in current dir
-	elif [ "$action" == "get" ] && [ -f ${package}_recipe.sh ]; then
-		echo -e "Recipe exist: ${YELLOW}$(pwd)/${package}_recipe.sh${NC}"
+	elif [ "$action" == "get" ] && [ -f ${pkg}_recipe.sh ]; then
+		echo -e "Recipe exist: ${YELLOW}$(pwd)/${pkg}_recipe.sh${NC}"
 	
 	# Get and install recipe if needed
-	elif [ "$action" == "install" ] && [ ! -f ${PKGS_RECIPES}/${package}_recipe.sh ]; then
-		echo "Downloading $package recipe..."
+	elif [ "$action" == "install" ] && [ ! -f ${PKGS_RECIPES}/${pkg}_recipe.sh ] && [ ! -f ${pkg}_recipe.sh ]; then
+		echo "Downloading $pkg recipe..."
 		cd ${PKGS_RECIPES}
-		wget -q --show-progress ${PKGS_RECIPES_URL}/${package}_recipe.sh
+		wget -q --show-progress ${PKGS_RECIPES_URL}/${pkg}_recipe.sh
 	fi
 }
 
@@ -1649,20 +1661,21 @@ pkg_source_recipe() {
 # First check sli itself, then load a custom recipe, and finaly use 
 # built-in function.
 pkg_install() {
-	if [ "$2" == "sli" ]; then
+	local pkg="$1"
+	if [ "$pkg" == "sli" ]; then
 		echo "If you need to reinstall this version, run: sli init"
 		echo "" && exit 0
 	fi
 	# Use built-in package
-	if [ $(declare -F ${2}_install) ]; then
-		${2}_install
+	if [ $(declare -F ${pkg}_install) ]; then
+		${pkg}_install
 	else
-		pkg_get_recipe "install" "$2"
-		pkg_source_recipe "$2"
-		if [ ! $(declare -F ${2}_install) ]; then
-			error "Missing: ${2}_install in recipe\n"
+		pkg_get_recipe "install" "$pkg"
+		pkg_source_recipe "$pkg"
+		if [ ! $(declare -F ${pkg}_install) ]; then
+			error "Missing: ${pkg}_install in recipe\n"
 		fi
-		${2}_install
+		${pkg}_install
 	fi
 }
 
@@ -1832,7 +1845,7 @@ pkgs_upgrade() {
 
 # Remove system files keep config/data in ~/.*
 pkg_remove() {
-	pkg="$1"
+	local pkg="$1"
 	[ -d ${INSTALLED_PKGS}/${pkg} ] || error "Can't find package: ${RED}$pkg${NC}"
 	print_header "⚡️ Removing package: $pkg"
 	for file in $(cat ${INSTALLED_PKGS}/${pkg}/files.list); do
@@ -1950,7 +1963,7 @@ handle_command() {
 		ping-amboss) ping_amboss ;;
 		wa|wallet) wallet ${@} ;;
 		# --- Packages manager ---
-		'in'|install) pkg_install ${@} ;;
+		'in'|install) pkg_install ${2} ;;
 		ls|list) pkgs_list ;;
 		gr|get-recipe) pkg_get_recipe "get" ${2} ;;
 		up|upgrade) pkgs_upgrade ;;
@@ -1958,6 +1971,8 @@ handle_command() {
 		cc|clean-cache)
 			echo "Removing cache directory content..."
 			rm -rf ${CACHE_DIR}/* ;;
+		# --- Developer Tools ---
+		testsuite) sli_testsuite ;;
 		*) usage ;;
 	esac
 }
